class RegisterConstants:
    DATA_SIZE = 200
    RETURN_ADDRESS = 1000
    RETURN_VALUE = 1004
    STACK_POINTER = 1008
    STACK_START = 0
    DATA_START = 500
    BYTE_SIZE = 4
    MAIN_JP = 2 + DATA_SIZE
    PB_START = 3 + DATA_SIZE
